# Se existirem variáveis na Nuvem, usa-as. Senão, usa os valores por defeito (H2) locais.
spring.datasource.url=${DB_URL:jdbc:h2:mem:splittripdb}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# O Hibernate vai criar as tabelas automaticamente na base de dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.show-sql=true

# Resolve problemas de formatação de JSON no output
spring.jackson.serialization.fail-on-empty-beans=false